### ISSUE TITLE
Help with leds

### ISSUE THREAD

**Issue by fabioluciano** [Keycapsss/Lily58L-Build-Guide#4]
My name is Fábio, I'm from Brazil and recently I bought 3 lily58l plates.

I finished the building, but I have a issue with leds.

![IMG_20210528_005338.jpg](https://user-images.githubusercontent.com/499057/119927564-05c4bb00-bf50-11eb-8550-7ade6ca32932.jpg)

I replaced l5 3 times and the problem persist. Just this four leds turned on.

**Comment by fabioluciano** [comment]
There is any way to jump the l5 led? I just think that the PCB comes with some sorta issue. Maybe in transport. They came with a lot of scratches.

**Comment by LeiTi34** [comment]
You could also try resoldering L4. When I had problems with the LEDs it was because of a bad solder joint.

**Comment by LeiTi34** [comment]
If this does not work, you can measure the connections according to the [scematic](https://raw.githubusercontent.com/Keycapsss/Lily58L-Build-Guide/master/img/Lily58L-schematic.png).

**Comment by BenRoe** [comment]
All LEDs should light up red. If a LED does not light up or in a different color, try to reflow/replace this led, or the led before.
